sudo: false
dist: trusty

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

before_install:
  - python -V
  - pip -V

install:
  - sudo apt-get install gcc-4.7 g++-4.7 python-numpy libicu-dev
  - pip install -r requirements.txt

script: nosetests
